# Generated by Django 3.0.5 on 2020-05-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200508_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.Round'),
        ),
    ]
