# Generated by Django 3.0.5 on 2020-05-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200508_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplayers', to='api.Game'),
        ),
    ]
