# Generated by Django 3.0.5 on 2020-05-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200508_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='repeat_highest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='repeat_one',
            field=models.BooleanField(default=False),
        ),
    ]
