# Generated by Django 3.0.5 on 2020-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200510_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='hand',
            field=models.BooleanField(default=False),
        ),
    ]
