# Generated by Django 3.0.5 on 2020-05-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bet_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='hand',
            field=models.CharField(choices=[('', ''), ('Hand', 'Hand'), ('Dessert', 'Dessert')], default='', max_length=10),
        ),
    ]
