# Generated by Django 3.0.5 on 2020-05-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200510_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='hand',
            field=models.CharField(choices=[('', ''), ('hand', 'hand'), ('dessert', 'dessert')], default='', max_length=10),
        ),
    ]
