# Generated by Django 3.0.5 on 2020-05-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200510_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ['id']},
        ),
    ]
