# Generated by Django 3.0.5 on 2020-05-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200510_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={},
        ),
    ]
