# Generated by Django 3.0.5 on 2020-05-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200510_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ['id']},
        ),
    ]
