# Generated by Django 3.0.5 on 2020-05-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200511_2016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
    ]
