# Generated by Django 3.0.5 on 2020-05-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200511_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.Tournament'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('id', 'tournament')},
        ),
    ]
