# Generated by Django 3.0.5 on 2020-05-13 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200511_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
