# Generated by Django 3.0.6 on 2020-05-21 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200513_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='bet',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='won',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 21)),
        ),
    ]
