# Generated by Django 3.0.6 on 2020-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200521_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ['score', 'id']},
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='won',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
