# Generated by Django 3.0.6 on 2020-05-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200523_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ['-score', 'id']},
        ),
    ]
