# Generated by Django 3.0.6 on 2020-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200523_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
