# Generated by Django 3.2.6 on 2021-12-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200524_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='bet',
            name='phase',
            field=models.CharField(blank=True, choices=[('ascending', 'ascending'), ('max_cards', 'max_cards'), ('descending', 'descending')], default='ascending', max_length=11),
        ),
        migrations.AddField(
            model_name='bet',
            name='position',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='result',
            field=models.CharField(blank=True, choices=[('winner', 'winner'), ('podium', 'podium'), ('last', 'last'), ('other', 'other')], default='other', max_length=7),
        ),
    ]
