# Generated by Django 3.2.6 on 2022-01-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_gameplayer_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
